In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/mumbai_house_prices.csv")
df.shape
df.columns
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76038 entries, 0 to 76037
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bhk         76038 non-null  int64
 1   type        76038 non-null  str
 2   locality    76038 non-null  str
 3   area        76038 non-null  int64
 4   price       76038 non-null  float64
 5   price_unit  76038 non-null  str
 6   region      76038 non-null  str
 7   status      76038 non-null  str
 8   age         76038 non-null  str
dtypes: float64(1), int64(2), str(6)
memory usage: 5.2 MB

In [3]:
df_clean = df.copy()
#df_clean.duplicated().sum()
df_clean[df_clean.duplicated()]

,bhk,type,locality,area,price,price_unit,region,status,age
49,3,Apartment,Lak And Hanware The Residency Tower,685,2.50,Cr,Andheri West,Ready to move,New
50,2,Apartment,Radheya Sai Enclave Building No 2,640,52.51,L,Naigaon East,Under Construction,New
51,2,Apartment,Romell Serene,610,1.73,Cr,Borivali West,Under Construction,New
52,2,Apartment,Soundlines Codename Urban Rainforest,876,59.98,L,Panvel,Under Construction,New
53,2,Apartment,Origin Oriana,659,94.11,L,Mira Road East,Under Construction,New
...,...,...,...,...,...,...,...,...,...
76023,2,Apartment,NARANG REALTY And WADHWA GROUP Courtyard,706,1.66,Cr,Thane West,Ready to move,New
76024,3,Apartment,NARANG REALTY And WADHWA GROUP Courtyard,1091,2.80,Cr,Thane West,Ready to move,New
76027,3,Apartment,Dosti West County,1115,1.52,Cr,Thane West,Under Construction,New
76028,2,Apartment,Dosti West County,639,87.47,L,Thane West,Under Construction,New
76029,2,Apartment,Dosti West County,550,75.26,L,Thane West,Under Construction,New

In [4]:
print("orignal dataset shape" , df.shape)

orignal dataset shape (76038, 9)

In [9]:
duplicate_count = df_clean.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)
df_clean[df_clean.duplicated(keep=False)]

Number of duplicate rows: 20312

,bhk,type,locality,area,price,price_unit,region,status,age
0,3,Apartment,Lak And Hanware The Residency Tower,685,2.50,Cr,Andheri West,Ready to move,New
1,2,Apartment,Radheya Sai Enclave Building No 2,640,52.51,L,Naigaon East,Under Construction,New
2,2,Apartment,Romell Serene,610,1.73,Cr,Borivali West,Under Construction,New
3,2,Apartment,Soundlines Codename Urban Rainforest,876,59.98,L,Panvel,Under Construction,New
4,2,Apartment,Origin Oriana,659,94.11,L,Mira Road East,Under Construction,New
...,...,...,...,...,...,...,...,...,...
76023,2,Apartment,NARANG REALTY And WADHWA GROUP Courtyard,706,1.66,Cr,Thane West,Ready to move,New
76024,3,Apartment,NARANG REALTY And WADHWA GROUP Courtyard,1091,2.80,Cr,Thane West,Ready to move,New
76027,3,Apartment,Dosti West County,1115,1.52,Cr,Thane West,Under Construction,New
76028,2,Apartment,Dosti West County,639,87.47,L,Thane West,Under Construction,New
76029,2,Apartment,Dosti West County,550,75.26,L,Thane West,Under Construction,New

In [22]:
print("Original rows:", len(df_clean))
print("Rows involved in duplicate groups:", df_clean.duplicated(keep=False).sum())
print("Duplicate rows beyond first occurrence:", df_clean.duplicated().sum())

Original rows: 76038
Rows involved in duplicate groups: 29128
Duplicate rows beyond first occurrence: 20312

In [23]:
dupe_counts = df_clean.value_counts(dropna=False)

dupe_counts[dupe_counts > 1].head(20)

bhk  type       locality                          area  price  price_unit  region        status         age
1    Apartment  Reputed Builder Wild Wood Park 2  651   20.00  L           Andheri West  Ready to move  Resale     267
4    Apartment  Sheth Avalon                      2579  4.50   Cr          Thane West    Ready to move  Unknown    157
3    Apartment  Hiranandani Meadows               1750  3.25   Cr          Thane West    Ready to move  Unknown    107
2    Apartment  Cosmos Horizon                    1065  1.35   Cr          Thane West    Ready to move  Unknown     94
3    Apartment  Neelkanth Greens                  1650  1.90   Cr          Thane West    Ready to move  Unknown     87
2    Apartment  DSS Mahavir Millennium            1025  1.25   Cr          Thane West    Ready to move  Unknown     84
                ACME Ozone Phase 2                1065  1.15   Cr          Thane West    Ready to move  Unknown     83
4    Apartment  T Bhimjyani The Verraton          1950  2.65   Cr          Thane West    Ready to move  Unknown     79
3    Apartment  ACME Ozone Phase 2                1650  1.55   Cr          Thane West    Ready to move  Unknown     74
5    Apartment  Hiranandani Estate                5868  8.50   Cr          Thane West    Ready to move  Unknown     68
4    Apartment  Hiranandani Meadows               2650  5.30   Cr          Thane West    Ready to move  Unknown     68
3    Apartment  Cosmos Horizon                    1650  2.00   Cr          Thane West    Ready to move  Unknown     65
2    Apartment  Kalpataru Hills                   1065  1.15   Cr          Thane West    Ready to move  Unknown     64
                Sheth Avalon                      1250  1.75   Cr          Thane West    Ready to move  Unknown     61
3    Apartment  Runwal Garden City Dahlia         1640  1.90   Cr          Thane West    Ready to move  Unknown     57
4    Apartment  Kalpataru Siddhachal Elegant      2815  4.00   Cr          Thane West    Ready to move  Unknown     54
3    Apartment  Runwal Garden City Dahlia         1532  1.60   Cr          Thane West    Ready to move  Unknown     53
                Hiranandani Meadows               1400  2.50   Cr          Thane West    Ready to move  Unknown     52
4    Apartment  ACME Ozone Phase 2                2200  2.60   Cr          Thane West    Ready to move  Unknown     51
                T Bhimjyani The Verraton          1950  3.15   Cr          Thane West    Ready to move  Unknown     47
Name: count, dtype: int64

In [25]:
dupes = df_clean[df_clean.duplicated(keep=False)]

dupes.sort_values(by=list(df_clean.columns)).head(20)

,bhk,type,locality,area,price,price_unit,region,status,age
33348,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
33548,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
33627,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
34154,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
4898,1,Apartment,Radhe Krishna Heights,480,22.5,L,Karjat,Ready to move,New
5063,1,Apartment,Radhe Krishna Heights,480,22.5,L,Karjat,Ready to move,New
4810,1,Apartment,Radhe Krishna Heights,500,23.9,L,Karjat,Ready to move,New
4821,1,Apartment,Radhe Krishna Heights,500,23.9,L,Karjat,Ready to move,New
4703,1,Apartment,Radhe Krishna Heights,500,24.8,L,Karjat,Ready to move,New
5236,1,Apartment,Radhe Krishna Heights,500,24.8,L,Karjat,Ready to move,New
5245,1,Apartment,Radhe Krishna Heights,500,24.8,L,Karjat,Ready to move,New
5423,1,Apartment,Radhe Krishna Heights,510,22.5,L,Karjat,Ready to move,New
5444,1,Apartment,Radhe Krishna Heights,510,22.5,L,Karjat,Ready to move,New
5224,1,Apartment,Radhe Krishna Heights,520,23.0,L,Karjat,Ready to move,New
5332,1,Apartment,Radhe Krishna Heights,520,23.0,L,Karjat,Ready to move,New
5342,1,Apartment,Radhe Krishna Heights,520,23.0,L,Karjat,Ready to move,New
13780,1,Apartment,Riddhi Siddhi Apartment,571,42.0,L,Kalyan West,Ready to move,Resale
13786,1,Apartment,Riddhi Siddhi Apartment,571,42.0,L,Kalyan West,Ready to move,Resale
67950,1,Apartment,Sanskar Dham,660,22.5,L,Badlapur,Ready to move,Unknown
67973,1,Apartment,Sanskar Dham,660,22.5,L,Badlapur,Ready to move,Unknown

In [26]:
dupes = df_clean[df_clean.duplicated(keep=False)]

dupes_sorted = dupes.sort_values(by=list(df_clean.columns))

dupes_sorted.head(20)

,bhk,type,locality,area,price,price_unit,region,status,age
33348,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
33548,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
33627,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
34154,1,Apartment,Dwarkesh Dham C H S,600,90.0,L,Dahisar West,Ready to move,Resale
4898,1,Apartment,Radhe Krishna Heights,480,22.5,L,Karjat,Ready to move,New
5063,1,Apartment,Radhe Krishna Heights,480,22.5,L,Karjat,Ready to move,New
4810,1,Apartment,Radhe Krishna Heights,500,23.9,L,Karjat,Ready to move,New
4821,1,Apartment,Radhe Krishna Heights,500,23.9,L,Karjat,Ready to move,New
4703,1,Apartment,Radhe Krishna Heights,500,24.8,L,Karjat,Ready to move,New
5236,1,Apartment,Radhe Krishna Heights,500,24.8,L,Karjat,Ready to move,New
5245,1,Apartment,Radhe Krishna Heights,500,24.8,L,Karjat,Ready to move,New
5423,1,Apartment,Radhe Krishna Heights,510,22.5,L,Karjat,Ready to move,New
5444,1,Apartment,Radhe Krishna Heights,510,22.5,L,Karjat,Ready to move,New
5224,1,Apartment,Radhe Krishna Heights,520,23.0,L,Karjat,Ready to move,New
5332,1,Apartment,Radhe Krishna Heights,520,23.0,L,Karjat,Ready to move,New
5342,1,Apartment,Radhe Krishna Heights,520,23.0,L,Karjat,Ready to move,New
13780,1,Apartment,Riddhi Siddhi Apartment,571,42.0,L,Kalyan West,Ready to move,Resale
13786,1,Apartment,Riddhi Siddhi Apartment,571,42.0,L,Kalyan West,Ready to move,Resale
67950,1,Apartment,Sanskar Dham,660,22.5,L,Badlapur,Ready to move,Unknown
67973,1,Apartment,Sanskar Dham,660,22.5,L,Badlapur,Ready to move,Unknown

In [27]:
duplicate_groups = df_clean.value_counts(dropna=False)

duplicate_groups[duplicate_groups > 1].head(20)

bhk  type       locality                          area  price  price_unit  region        status         age
1    Apartment  Reputed Builder Wild Wood Park 2  651   20.00  L           Andheri West  Ready to move  Resale     267
4    Apartment  Sheth Avalon                      2579  4.50   Cr          Thane West    Ready to move  Unknown    157
3    Apartment  Hiranandani Meadows               1750  3.25   Cr          Thane West    Ready to move  Unknown    107
2    Apartment  Cosmos Horizon                    1065  1.35   Cr          Thane West    Ready to move  Unknown     94
3    Apartment  Neelkanth Greens                  1650  1.90   Cr          Thane West    Ready to move  Unknown     87
2    Apartment  DSS Mahavir Millennium            1025  1.25   Cr          Thane West    Ready to move  Unknown     84
                ACME Ozone Phase 2                1065  1.15   Cr          Thane West    Ready to move  Unknown     83
4    Apartment  T Bhimjyani The Verraton          1950  2.65   Cr          Thane West    Ready to move  Unknown     79
3    Apartment  ACME Ozone Phase 2                1650  1.55   Cr          Thane West    Ready to move  Unknown     74
5    Apartment  Hiranandani Estate                5868  8.50   Cr          Thane West    Ready to move  Unknown     68
4    Apartment  Hiranandani Meadows               2650  5.30   Cr          Thane West    Ready to move  Unknown     68
3    Apartment  Cosmos Horizon                    1650  2.00   Cr          Thane West    Ready to move  Unknown     65
2    Apartment  Kalpataru Hills                   1065  1.15   Cr          Thane West    Ready to move  Unknown     64
                Sheth Avalon                      1250  1.75   Cr          Thane West    Ready to move  Unknown     61
3    Apartment  Runwal Garden City Dahlia         1640  1.90   Cr          Thane West    Ready to move  Unknown     57
4    Apartment  Kalpataru Siddhachal Elegant      2815  4.00   Cr          Thane West    Ready to move  Unknown     54
3    Apartment  Runwal Garden City Dahlia         1532  1.60   Cr          Thane West    Ready to move  Unknown     53
                Hiranandani Meadows               1400  2.50   Cr          Thane West    Ready to move  Unknown     52
4    Apartment  ACME Ozone Phase 2                2200  2.60   Cr          Thane West    Ready to move  Unknown     51
                T Bhimjyani The Verraton          1950  3.15   Cr          Thane West    Ready to move  Unknown     47
Name: count, dtype: int64

In [28]:
print("Total rows:", len(df_clean))
print("Unique rows:", df_clean.drop_duplicates().shape[0])
print("Rows that would be removed:", len(df_clean) - len(df_clean.drop_duplicates()))

Total rows: 76038
Unique rows: 55726
Rows that would be removed: 20312

In [29]:
df_clean = df_clean.drop_duplicates()
print("Rows after removing duplicates:", len(df_clean))
print("Duplicates remaining:", df_clean.duplicated().sum())

Rows after removing duplicates: 55726
Duplicates remaining: 0

In [37]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [38]:
df_clean.columns

Index(['bhk', 'type', 'locality', 'area', 'price', 'price_unit', 'region',
       'status', 'age'],
      dtype='str')

In [42]:
df_clean.isnull().sum()

bhk           0
type          0
locality      0
area          0
price         0
price_unit    0
region        0
status        0
age           0
dtype: int64

In [43]:
missing_percentage = df_clean.isnull().mean() * 100
missing_percentage.sort_values(ascending=False)

bhk           0.0
type          0.0
locality      0.0
area          0.0
price         0.0
price_unit    0.0
region        0.0
status        0.0
age           0.0
dtype: float64

In [44]:
df_clean.dtypes

bhk             int64
type              str
locality          str
area            int64
price         float64
price_unit        str
region            str
status            str
age               str
dtype: object

In [45]:
df_clean.describe()

                bhk          area         price
count  55726.000000  55726.000000  55726.000000
mean       1.941930    985.728152     31.124466
std        0.888328    608.996691     33.172304
min        1.000000    127.000000      1.000000
25%        1.000000    645.000000      1.800000
50%        2.000000    854.500000     11.000000
75%        2.000000   1150.000000     60.642500
max       10.000000  16000.000000     99.990000

In [46]:
df_clean["bhk"].value_counts().sort_index()

bhk
1     19349
2     23609
3     10109
4      2165
5       370
6        92
7        13
8         8
9         5
10        6
Name: count, dtype: int64

In [50]:
df_clean["area"].describe()

count    55726.000000
mean       985.728152
std        608.996691
min        127.000000
25%        645.000000
50%        854.500000
75%       1150.000000
max      16000.000000
Name: area, dtype: float64

In [51]:
df_clean[df_clean["area"] <= 0]

Empty DataFrame
Columns: [bhk, type, locality, area, price, price_unit, region, status, age]
Index: []

In [52]:
df_clean["price"].describe()

count    55726.000000
mean        31.124466
std         33.172304
min          1.000000
25%          1.800000
50%         11.000000
75%         60.642500
max         99.990000
Name: price, dtype: float64

In [53]:
df_clean["price"].dtype

dtype('float64')

In [54]:
df_clean["price"].head(10)

0     2.50
1    52.51
2     1.73
3    59.98
4    94.11
5     3.30
6     1.99
7     2.89
8    29.84
9     2.72
Name: price, dtype: float64

In [55]:
df_clean["type"].value_counts()

type
Apartment            54782
Studio Apartment       728
Villa                  154
Independent House       59
Penthouse                3
Name: count, dtype: int64

In [56]:
df_clean["type"].nunique()

5

In [57]:
df_clean["locality"].value_counts().head(20)

locality
JP North Barcelona                254
Lodha Codename Premier            207
Amar Vinay Heritage               196
Raj Akshay                        193
JP Codename Dream Home Tower B    192
Runwal Gardens                    192
JK IRIS                           163
JP Codename Dream Home Tower C    161
Umiya Oasis                       153
Hiranandani Meadows               146
Kalpataru Srishti Namaah          139
Runwal Bliss                      139
Unique Ivana                      138
Lodha Codename Crown Jewel        131
JP North Barcelona Wing D         131
Shree Ramdev Heights              131
Nandkumar Janki Legacy            128
Vasant Vasant Vihar               126
MICL Aradhya D And E Tower        123
Sanghvi Ecocity Phase 3           122
Name: count, dtype: int64

In [58]:
df_clean["locality"].nunique()

9782

In [62]:
print("DATA TYPES")
print(df_clean.dtypes)

print("\nNUMERICAL SUMMARY")
print(df_clean.describe())

DATA TYPES
bhk             int64
type              str
locality          str
area            int64
price         float64
price_unit        str
region            str
status            str
age               str
dtype: object

NUMERICAL SUMMARY
                bhk          area         price
count  55726.000000  55726.000000  55726.000000
mean       1.941930    985.728152     31.124466
std        0.888328    608.996691     33.172304
min        1.000000    127.000000      1.000000
25%        1.000000    645.000000      1.800000
50%        2.000000    854.500000     11.000000
75%        2.000000   1150.000000     60.642500
max       10.000000  16000.000000     99.990000

In [63]:
print("BHK DISTRIBUTION")
print(df_clean["bhk"].value_counts().sort_index())

print("\nPROPERTY TYPES")
print(df_clean["type"].value_counts())

print("\nNUMBER OF PROPERTY TYPES")
print(df_clean["type"].nunique())

BHK DISTRIBUTION
bhk
1     19349
2     23609
3     10109
4      2165
5       370
6        92
7        13
8         8
9         5
10        6
Name: count, dtype: int64

PROPERTY TYPES
type
Apartment            54782
Studio Apartment       728
Villa                  154
Independent House       59
Penthouse                3
Name: count, dtype: int64

NUMBER OF PROPERTY TYPES
5

In [67]:
print("PRICE DATA TYPE")
print(df_clean["price"].dtype)

print("\nPRICE SUMMARY")
print(df_clean["price"].describe())

print("\nFIRST 10 PRICE VALUES")
print(df_clean["price"].head(10))

print("\nPRICE UNITS")
print(df_clean["price_unit"].value_counts())

PRICE DATA TYPE
float64

PRICE SUMMARY
count    55726.000000
mean        31.124466
std         33.172304
min          1.000000
25%          1.800000
50%         11.000000
75%         60.642500
max         99.990000
Name: price, dtype: float64

FIRST 10 PRICE VALUES
0     2.50
1    52.51
2     1.73
3    59.98
4    94.11
5     3.30
6     1.99
7     2.89
8    29.84
9     2.72
Name: price, dtype: float64

PRICE UNITS
price_unit
Cr    28363
L     27363
Name: count, dtype: int64

In [68]:
print("TOP 20 LOCALITIES")
print(df_clean["locality"].value_counts().head(20))

print("\nNUMBER OF UNIQUE LOCALITIES")
print(df_clean["locality"].nunique())

TOP 20 LOCALITIES
locality
JP North Barcelona                254
Lodha Codename Premier            207
Amar Vinay Heritage               196
Raj Akshay                        193
JP Codename Dream Home Tower B    192
Runwal Gardens                    192
JK IRIS                           163
JP Codename Dream Home Tower C    161
Umiya Oasis                       153
Hiranandani Meadows               146
Kalpataru Srishti Namaah          139
Runwal Bliss                      139
Unique Ivana                      138
Lodha Codename Crown Jewel        131
JP North Barcelona Wing D         131
Shree Ramdev Heights              131
Nandkumar Janki Legacy            128
Vasant Vasant Vihar               126
MICL Aradhya D And E Tower        123
Sanghvi Ecocity Phase 3           122
Name: count, dtype: int64

NUMBER OF UNIQUE LOCALITIES
9782

In [69]:
df_clean.to_csv("../data/raw_cleaned.csv", index=False)

In [70]:
import os

print(os.path.exists("../data/raw_cleaned.csv"))

True

In [71]:
cleaned_df = pd.read_csv("../data/raw_cleaned.csv")

In [73]:
print(cleaned_df.shape)
print(cleaned_df.head())

(55726, 9)
   bhk       type                              locality  area  price  \
0    3  Apartment   Lak And Hanware The Residency Tower   685   2.50
1    2  Apartment     Radheya Sai Enclave Building No 2   640  52.51
2    2  Apartment                         Romell Serene   610   1.73
3    2  Apartment  Soundlines Codename Urban Rainforest   876  59.98
4    2  Apartment                         Origin Oriana   659  94.11

  price_unit          region              status  age
0         Cr    Andheri West       Ready to move  New
1          L    Naigaon East  Under Construction  New
2         Cr   Borivali West  Under Construction  New
3          L          Panvel  Under Construction  New
4          L  Mira Road East  Under Construction  New

In [75]:
print("Rows:", len(cleaned_df))
print("Columns:", len(cleaned_df.columns))
print("Duplicates:", cleaned_df.duplicated().sum())
print("Missing values:", cleaned_df.isnull().sum().sum())

Rows: 55726
Columns: 9
Duplicates: 0
Missing values: 0

 Data Cleaning Summary

The original Mumbai housing dataset was inspected using pandas. Exact duplicate
rows were identified and removed, leaving 55,726 records. Column names were
standardized to lowercase with underscores. The dataset contained no missing
values after inspection. Data types, numerical variables, BHK distribution,
property types, area, price, and locality information were also examined.

The cleaned dataset was saved as `data/raw_cleaned.csv`.